import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="rootLayout" style={{backgroundColor:'pink',height:100}}>
          {children}
        </div>
      </body>
    </html>
  );
}
