import Footer from "./components/footer";
import NavBar from "./components/navbar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {/* Nav Bar  */}
        <NavBar />
        <hr />
        {/* Page content */}
        {children}
        {/* Footer Content */}
        <Footer />
      </body>
    </html>
  );
}
